"""
Hardcoded Nifty 500 constituent list — last-resort fallback only.

This list reflects constituents as of July 2026. Update manually when needed.
Format: (NSE_SYMBOL, COMPANY_NAME, INDUSTRY)
The fetch order in constituents.py tries NSE URL → direct HTTP → this list last.
"""

NIFTY500_STATIC: list[tuple[str, str, str]] = [
    ("360ONE", "360 ONE WAM LIMITED", "Financial Services"),
    ("3MINDIA", "3M India Ltd", "Diversified"),
    ("ABB", "ABB India Ltd", "Capital Goods"),
    ("ABBOTINDIA", "Abbott India Ltd", "Healthcare"),
    ("ABCAPITAL", "Aditya Birla Capital Ltd", "Financial Services"),
    ("ABFRL", "Aditya Birla Fashion and Retail Ltd", "Textile"),
    ("ACC", "ACC Ltd", "Cement & Cement Products"),
    ("ACMESOLAR", "Acme Solar Holdings Ltd", "Power"),
    ("ADANIBSE", "Adani Enterprises Ltd", "Metals & Mining"),
    ("ADANIENSOL", "Adani Energy Solutions Ltd", "Power"),
    ("ADANIGREEN", "Adani Green Energy Ltd", "Power"),
    ("ADANIPORTS", "Adani Ports and Special Economic Zone Ltd", "Services"),
    ("ADANIPOWER", "Adani Power Ltd", "Power"),
    ("ADANITRANS", "Adani Transmission Ltd", "Power"),
    ("AFFLE", "Affle (India) Ltd", "IT"),
    ("AJANTPHARM", "Ajanta Pharma Ltd", "Healthcare"),
    ("AKUMS", "Akums Drugs and Pharmaceuticals Ltd", "Healthcare"),
    ("ALKEM", "Alkem Laboratories Ltd", "Healthcare"),
    ("ALKYLAMINE", "Alkyl Amines Chemicals Ltd", "Chemicals"),
    ("ALLCARGO", "Allcargo Logistics Ltd", "Services"),
    ("ALOKINDS", "Alok Industries Ltd", "Textile"),
    ("AMARA", "Amara Raja Energy & Mobility Ltd", "Automobile and Auto Components"),
    ("AMBUJACEMENT", "Ambuja Cements Ltd", "Cement & Cement Products"),
    ("AMIORG", "Ami Organics Ltd", "Chemicals"),
    ("AMNSIND", "AM/NS India Ltd", "Metals & Mining"),
    ("ANGELONE", "Angel One Ltd", "Financial Services"),
    ("ANURAS", "Anupam Rasayan India Ltd", "Chemicals"),
    ("APARINDS", "Apar Industries Ltd", "Capital Goods"),
    ("APLLTD", "APL Apollo Tubes Ltd", "Metals & Mining"),
    ("APOLLOHOSP", "Apollo Hospitals Enterprise Ltd", "Healthcare"),
    ("APOLLOTYRE", "Apollo Tyres Ltd", "Automobile and Auto Components"),
    ("APTUS", "Aptus Value Housing Finance India Ltd", "Financial Services"),
    ("ASHOKLEY", "Ashok Leyland Ltd", "Automobile and Auto Components"),
    ("ASIANPAINT", "Asian Paints Ltd", "Consumer Durables"),
    ("ASTERDM", "Aster DM Healthcare Ltd", "Healthcare"),
    ("ASTRAZEN", "AstraZeneca Pharma India Ltd", "Healthcare"),
    ("ASTRAL", "Astral Ltd", "Capital Goods"),
    ("AUROPHARMA", "Aurobindo Pharma Ltd", "Healthcare"),
    ("AVANTIFEED", "Avanti Feeds Ltd", "FMCG"),
    ("AXISBANK", "Axis Bank Ltd", "Financial Services"),
    ("BAJAJ-AUTO", "Bajaj Auto Ltd", "Automobile and Auto Components"),
    ("BAJAJFINSV", "Bajaj Finserv Ltd", "Financial Services"),
    ("BAJAJHFL", "Bajaj Housing Finance Ltd", "Financial Services"),
    ("BAJFINANCE", "Bajaj Finance Ltd", "Financial Services"),
    ("BALRAMCHIN", "Balrampur Chini Mills Ltd", "FMCG"),
    ("BANKBARODA", "Bank of Baroda", "Financial Services"),
    ("BANKINDIA", "Bank of India", "Financial Services"),
    ("BATAINDIA", "Bata India Ltd", "Consumer Durables"),
    ("BAYERCROP", "Bayer Cropscience Ltd", "Chemicals"),
    ("BDL", "Bharat Dynamics Ltd", "Capital Goods"),
    ("BEL", "Bharat Electronics Ltd", "Capital Goods"),
    ("BERGEPAINT", "Berger Paints India Ltd", "Consumer Durables"),
    ("BHARATFORG", "Bharat Forge Ltd", "Capital Goods"),
    ("BHARTIARTL", "Bharti Airtel Ltd", "Telecom"),
    ("BHEL", "Bharat Heavy Electricals Ltd", "Capital Goods"),
    ("BIKAJI", "Bikaji Foods International Ltd", "FMCG"),
    ("BIOCON", "Biocon Ltd", "Healthcare"),
    ("BIRLACORPN", "Birla Corporation Ltd", "Cement & Cement Products"),
    ("BJFINANCE", "Bajaj Finance Ltd", "Financial Services"),
    ("BLUEDART", "Blue Dart Express Ltd", "Services"),
    ("BLUESTARCO", "Blue Star Ltd", "Consumer Durables"),
    ("BPCL", "Bharat Petroleum Corporation Ltd", "Oil Gas & Consumable Fuels"),
    ("BRIGADE", "Brigade Enterprises Ltd", "Realty"),
    ("BSE", "BSE Ltd", "Financial Services"),
    ("BSOFT", "BIRLASOFT Ltd", "IT"),
    ("CAMS", "Computer Age Management Services Ltd", "Financial Services"),
    ("CANFINHOME", "Can Fin Homes Ltd", "Financial Services"),
    ("CANBK", "Canara Bank", "Financial Services"),
    ("CAPLIPOINT", "Caplin Point Laboratories Ltd", "Healthcare"),
    ("CARBORUNIV", "Carborundum Universal Ltd", "Capital Goods"),
    ("CASTROLIND", "Castrol India Ltd", "Oil Gas & Consumable Fuels"),
    ("CCL", "CCL Products (India) Ltd", "FMCG"),
    ("CEATLTD", "CEAT Ltd", "Automobile and Auto Components"),
    ("CENTRALBK", "Central Bank of India", "Financial Services"),
    ("CENTURYPLY", "Century Plyboards (India) Ltd", "Capital Goods"),
    ("CENTURYTEX", "Century Textiles & Industries Ltd", "Textile"),
    ("CESC", "CESC Ltd", "Power"),
    ("CGPOWER", "CG Power and Industrial Solutions Ltd", "Capital Goods"),
    ("CHALET", "Chalet Hotels Ltd", "Consumer Services"),
    ("CHAMBLFERT", "Chambal Fertilisers and Chemicals Ltd", "Chemicals"),
    ("CHOLAFIN", "Cholamandalam Investment and Finance Company Ltd", "Financial Services"),
    ("CHOLAHLDNG", "Cholamandalam Financial Holdings Ltd", "Financial Services"),
    ("CIPLA", "Cipla Ltd", "Healthcare"),
    ("CLEAN", "Clean Science and Technology Ltd", "Chemicals"),
    ("COALINDIA", "Coal India Ltd", "Oil Gas & Consumable Fuels"),
    ("COCHINSHIP", "Cochin Shipyard Ltd", "Capital Goods"),
    ("COFORGE", "Coforge Ltd", "IT"),
    ("COLPAL", "Colgate-Palmolive (India) Ltd", "FMCG"),
    ("CONCOR", "Container Corporation of India Ltd", "Services"),
    ("COROMANDEL", "Coromandel International Ltd", "Chemicals"),
    ("CREDITACC", "Creditaccess Grameen Ltd", "Financial Services"),
    ("CROMPTON", "Crompton Greaves Consumer Electricals Ltd", "Consumer Durables"),
    ("CUMMINSIND", "Cummins India Ltd", "Capital Goods"),
    ("CYIENT", "Cyient Ltd", "IT"),
    ("DALBHARAT", "Dalmia Bharat Ltd", "Cement & Cement Products"),
    ("DATAPATT", "Data Patterns (India) Ltd", "Capital Goods"),
    ("DEEPAKFERT", "Deepak Fertilisers and Petrochemicals Corporation Ltd", "Chemicals"),
    ("DEEPAKNTR", "Deepak Nitrite Ltd", "Chemicals"),
    ("DELHIVERY", "Delhivery Ltd", "Services"),
    ("DEVYANI", "Devyani International Ltd", "Consumer Services"),
    ("DIVISLAB", "Divi's Laboratories Ltd", "Healthcare"),
    ("DIXON", "Dixon Technologies (India) Ltd", "Consumer Durables"),
    ("DLF", "DLF Ltd", "Realty"),
    ("DMART", "Avenue Supermarts Ltd", "Consumer Services"),
    ("DRHREDDY", "Dr Reddy's Laboratories Ltd", "Healthcare"),
    ("EDELWEISS", "Edelweiss Financial Services Ltd", "Financial Services"),
    ("EGBF", "SBFC Finance Ltd", "Financial Services"),
    ("EMCURE", "Emcure Pharmaceuticals Ltd", "Healthcare"),
    ("EMKAY", "Emkay Global Financial Services Ltd", "Financial Services"),
    ("ENDURANCE", "Endurance Technologies Ltd", "Automobile and Auto Components"),
    ("ENGINERSIN", "Engineers India Ltd", "Capital Goods"),
    ("ERIS", "Eris Lifesciences Ltd", "Healthcare"),
    ("ESCORTS", "Escorts Kubota Ltd", "Capital Goods"),
    ("ETHANOLBSE", "Apar Industries Ltd", "Capital Goods"),
    ("EXIDEIND", "Exide Industries Ltd", "Automobile and Auto Components"),
    ("FACT", "Fertilisers and Chemicals Travancore Ltd", "Chemicals"),
    ("FINEORG", "Fine Organic Industries Ltd", "Chemicals"),
    ("FINPIPE", "Finolex Industries Ltd", "Capital Goods"),
    ("FLUOROCHEM", "Gujarat Fluorochemicals Ltd", "Chemicals"),
    ("FORTIS", "Fortis Healthcare Ltd", "Healthcare"),
    ("FRETAIL", "Future Retail Ltd", "Consumer Services"),
    ("FSL", "Firstsource Solutions Ltd", "IT"),
    ("GAIL", "GAIL (India) Ltd", "Oil Gas & Consumable Fuels"),
    ("GALAXYSURF", "Galaxy Surfactants Ltd", "Chemicals"),
    ("GARFIBRES", "Garware Technical Fibres Ltd", "Textile"),
    ("GESHIP", "The Great Eastern Shipping Company Ltd", "Services"),
    ("GILLETTE", "Gillette India Ltd", "FMCG"),
    ("GLAND", "Gland Pharma Ltd", "Healthcare"),
    ("GLAXO", "GlaxoSmithKline Pharmaceuticals Ltd", "Healthcare"),
    ("GLENMARK", "Glenmark Pharmaceuticals Ltd", "Healthcare"),
    ("GNFC", "Gujarat Narmada Valley Fertilizers & Chemicals Ltd", "Chemicals"),
    ("GODREJAGRO", "Godrej Agrovet Ltd", "FMCG"),
    ("GODREJCP", "Godrej Consumer Products Ltd", "FMCG"),
    ("GODREJIND", "Godrej Industries Ltd", "Diversified"),
    ("GODREJPROP", "Godrej Properties Ltd", "Realty"),
    ("GRANULES", "Granules India Ltd", "Healthcare"),
    ("GRAPHITE", "Graphite India Ltd", "Capital Goods"),
    ("GRASIM", "Grasim Industries Ltd", "Cement & Cement Products"),
    ("GRINDWELL", "Grindwell Norton Ltd", "Capital Goods"),
    ("GRINFRA", "G R Infraprojects Ltd", "Construction"),
    ("GSFC", "Gujarat State Fertilizers & Chemicals Ltd", "Chemicals"),
    ("GSPL", "Gujarat State Petronet Ltd", "Oil Gas & Consumable Fuels"),
    ("GUJGASLTD", "Gujarat Gas Ltd", "Oil Gas & Consumable Fuels"),
    ("HAPPSTMNDS", "Happiest Minds Technologies Ltd", "IT"),
    ("HCLTECH", "HCL Technologies Ltd", "IT"),
    ("HDFCAMC", "HDFC Asset Management Company Ltd", "Financial Services"),
    ("HDFCBANK", "HDFC Bank Ltd", "Financial Services"),
    ("HDFCLIFE", "HDFC Life Insurance Company Ltd", "Financial Services"),
    ("HERITGFOOD", "Heritage Foods Ltd", "FMCG"),
    ("HEROMOTOCO", "Hero MotoCorp Ltd", "Automobile and Auto Components"),
    ("HFCL", "HFCL Ltd", "Telecom"),
    ("HGSINFRA", "HG Infra Engineering Ltd", "Construction"),
    ("HINDALCO", "Hindalco Industries Ltd", "Metals & Mining"),
    ("HINDCOPPER", "Hindustan Copper Ltd", "Metals & Mining"),
    ("HINDPETRO", "Hindustan Petroleum Corporation Ltd", "Oil Gas & Consumable Fuels"),
    ("HINDUNILVR", "Hindustan Unilever Ltd", "FMCG"),
    ("HUDCO", "Housing and Urban Development Corporation Ltd", "Financial Services"),
    ("IBREALEST", "Indiabulls Real Estate Ltd", "Realty"),
    ("ICICIBANK", "ICICI Bank Ltd", "Financial Services"),
    ("ICICIGI", "ICICI Lombard General Insurance Company Ltd", "Financial Services"),
    ("ICICIPRULI", "ICICI Prudential Life Insurance Company Ltd", "Financial Services"),
    ("IDBI", "IDBI Bank Ltd", "Financial Services"),
    ("IDFCFIRSTB", "IDFC First Bank Ltd", "Financial Services"),
    ("IEX", "Indian Energy Exchange Ltd", "Financial Services"),
    ("IGL", "Indraprastha Gas Ltd", "Oil Gas & Consumable Fuels"),
    ("IIFL", "IIFL Finance Ltd", "Financial Services"),
    ("IIMJOBS", "Quess Corp Ltd", "Services"),
    ("INDGN", "Indegene Ltd", "IT"),
    ("INDHOTEL", "The Indian Hotels Company Ltd", "Consumer Services"),
    ("INDIAMART", "Indiamart Intermesh Ltd", "IT"),
    ("INDIANB", "Indian Bank", "Financial Services"),
    ("INDIGO", "InterGlobe Aviation Ltd", "Services"),
    ("INDIGOPNTS", "Indigo Paints Ltd", "Consumer Durables"),
    ("INDUSINDBK", "IndusInd Bank Ltd", "Financial Services"),
    ("INDUSTOWER", "Indus Towers Ltd", "Telecom"),
    ("INFY", "Infosys Ltd", "IT"),
    ("INGERRAND", "Ingersoll-Rand (India) Ltd", "Capital Goods"),
    ("IOB", "Indian Overseas Bank", "Financial Services"),
    ("IOC", "Indian Oil Corporation Ltd", "Oil Gas & Consumable Fuels"),
    ("IPCALAB", "IPCA Laboratories Ltd", "Healthcare"),
    ("IRB", "IRB Infrastructure Developers Ltd", "Construction"),
    ("IRCTC", "Indian Railway Catering and Tourism Corporation Ltd", "Services"),
    ("IREDA", "Indian Renewable Energy Development Agency Ltd", "Financial Services"),
    ("IRFC", "Indian Railway Finance Corporation Ltd", "Financial Services"),
    ("ITC", "ITC Ltd", "FMCG"),
    ("ITI", "ITI Ltd", "Telecom"),
    ("J&KBANK", "Jammu & Kashmir Bank Ltd", "Financial Services"),
    ("JIOFIN", "Jio Financial Services Ltd", "Financial Services"),
    ("JSL", "Jindal Stainless Ltd", "Metals & Mining"),
    ("JSLHISAR", "Jindal Stainless (Hisar) Ltd", "Metals & Mining"),
    ("JSWENERGY", "JSW Energy Ltd", "Power"),
    ("JSWINFRA", "JSW Infrastructure Ltd", "Services"),
    ("JSWSTEEL", "JSW Steel Ltd", "Metals & Mining"),
    ("JUBLFOOD", "Jubilant Foodworks Ltd", "Consumer Services"),
    ("JUBLINGREA", "Jubilant Ingrevia Ltd", "Chemicals"),
    ("JUBLPHARMA", "Jubilant Pharmova Ltd", "Healthcare"),
    ("K.P.R.MILL", "K.P.R. Mill Ltd", "Textile"),
    ("KAJARIACER", "Kajaria Ceramics Ltd", "Consumer Durables"),
    ("KALPATPOWR", "Kalpataru Projects International Ltd", "Construction"),
    ("KANSAINER", "Kansai Nerolac Paints Ltd", "Consumer Durables"),
    ("KARURVYSYA", "Karur Vysya Bank Ltd", "Financial Services"),
    ("KEC", "KEC International Ltd", "Capital Goods"),
    ("KFIN", "KFin Technologies Ltd", "Financial Services"),
    ("KINETIC", "Kinetic Green Energy and Power Solutions Ltd", "Automobile and Auto Components"),
    ("KIRLOSCAR", "Kirloskar Brothers Ltd", "Capital Goods"),
    ("KIRLOSBROS", "Kirloskar Brothers Ltd", "Capital Goods"),
    ("KMBL", "Kotak Mahindra Bank Ltd", "Financial Services"),
    ("KOTAKBANK", "Kotak Mahindra Bank Ltd", "Financial Services"),
    ("KPITTECH", "KPIT Technologies Ltd", "IT"),
    ("KRBL", "KRBL Ltd", "FMCG"),
    ("KSB", "KSB Ltd", "Capital Goods"),
    ("L&TFH", "L&T Finance Ltd", "Financial Services"),
    ("LATENTVIEW", "LatentView Analytics Ltd", "IT"),
    ("LAURUSLABS", "Laurus Labs Ltd", "Healthcare"),
    ("LICI", "Life Insurance Corporation of India", "Financial Services"),
    ("LINDEINDIA", "Linde India Ltd", "Chemicals"),
    ("LT", "Larsen & Toubro Ltd", "Construction"),
    ("LTIM", "LTIMindtree Ltd", "IT"),
    ("LTTS", "L&T Technology Services Ltd", "IT"),
    ("LUPIN", "Lupin Ltd", "Healthcare"),
    ("M&M", "Mahindra & Mahindra Ltd", "Automobile and Auto Components"),
    ("M&MFIN", "Mahindra & Mahindra Financial Services Ltd", "Financial Services"),
    ("MAHABANK", "Bank of Maharashtra", "Financial Services"),
    ("MAHINDCIE", "Mahindra CIE Automotive Ltd", "Automobile and Auto Components"),
    ("MANAPPURAM", "Manappuram Finance Ltd", "Financial Services"),
    ("MARICO", "Marico Ltd", "FMCG"),
    ("MARUTI", "Maruti Suzuki India Ltd", "Automobile and Auto Components"),
    ("MASTEK", "Mastek Ltd", "IT"),
    ("MFSL", "Max Financial Services Ltd", "Financial Services"),
    ("MGMRESORTS", "EIH Ltd", "Consumer Services"),
    ("MINDACORP", "Minda Corporation Ltd", "Automobile and Auto Components"),
    ("MINDAIND", "Uno Minda Ltd", "Automobile and Auto Components"),
    ("MITCON", "MITCON Consultancy & Engineering Services Ltd", "Services"),
    ("MMTC", "MMTC Ltd", "Services"),
    ("MOIL", "MOIL Ltd", "Metals & Mining"),
    ("MOTHERSON", "Samvardhana Motherson International Ltd", "Automobile and Auto Components"),
    ("MPHASIS", "Mphasis Ltd", "IT"),
    ("MRF", "MRF Ltd", "Automobile and Auto Components"),
    ("MRPL", "Mangalore Refinery and Petrochemicals Ltd", "Oil Gas & Consumable Fuels"),
    ("MUTHOOTFIN", "Muthoot Finance Ltd", "Financial Services"),
    ("NATCOPHARM", "Natco Pharma Ltd", "Healthcare"),
    ("NAUKRI", "Info Edge (India) Ltd", "IT"),
    ("NAVINFLUOR", "Navin Fluorine International Ltd", "Chemicals"),
    ("NBCC", "NBCC (India) Ltd", "Construction"),
    ("NCC", "NCC Ltd", "Construction"),
    ("NESTLEIND", "Nestle India Ltd", "FMCG"),
    ("NETWORK18", "Network18 Media & Investments Ltd", "Media Publishing & Research"),
    ("NHPC", "NHPC Ltd", "Power"),
    ("NIACL", "The New India Assurance Company Ltd", "Financial Services"),
    ("NILKAMAL", "Nilkamal Ltd", "Consumer Durables"),
    ("NMDC", "NMDC Ltd", "Metals & Mining"),
    ("NOCIL", "NOCIL Ltd", "Chemicals"),
    ("NSLNISP", "NMDC Steel Ltd", "Metals & Mining"),
    ("NTPC", "NTPC Ltd", "Power"),
    ("NUVAMA", "Nuvama Wealth Management Ltd", "Financial Services"),
    ("NUVOCO", "Nuvoco Vistas Corporation Ltd", "Cement & Cement Products"),
    ("OIL", "Oil India Ltd", "Oil Gas & Consumable Fuels"),
    ("ONGC", "Oil and Natural Gas Corporation Ltd", "Oil Gas & Consumable Fuels"),
    ("ORIENTELEC", "Orient Electric Ltd", "Consumer Durables"),
    ("PAGEIND", "Page Industries Ltd", "Textile"),
    ("PATANJALI", "Patanjali Foods Ltd", "FMCG"),
    ("PAYTM", "One97 Communications Ltd", "Financial Services"),
    ("PEL", "Piramal Enterprises Ltd", "Financial Services"),
    ("PERSISTENT", "Persistent Systems Ltd", "IT"),
    ("PETRONET", "Petronet LNG Ltd", "Oil Gas & Consumable Fuels"),
    ("PFC", "Power Finance Corporation Ltd", "Financial Services"),
    ("PIDILITEIND", "Pidilite Industries Ltd", "Chemicals"),
    ("PIIND", "PI Industries Ltd", "Chemicals"),
    ("PNB", "Punjab National Bank", "Financial Services"),
    ("POLYCAB", "Polycab India Ltd", "Capital Goods"),
    ("POLYMED", "Poly Medicure Ltd", "Healthcare"),
    ("POONAWALLA", "Poonawalla Fincorp Ltd", "Financial Services"),
    ("POWERINDIA", "ABB Power Products and Systems India Ltd", "Capital Goods"),
    ("POWERGRID", "Power Grid Corporation of India Ltd", "Power"),
    ("PRESTIGE", "Prestige Estates Projects Ltd", "Realty"),
    ("PRINCEPIPE", "Prince Pipes and Fittings Ltd", "Capital Goods"),
    ("PVRINOX", "PVR INOX Ltd", "Consumer Services"),
    ("RAIN", "Rain Industries Ltd", "Chemicals"),
    ("RAJESHEXPO", "Rajesh Exports Ltd", "Consumer Durables"),
    ("RALLIS", "Rallis India Ltd", "Chemicals"),
    ("RKFORGE", "Ramkrishna Forgings Ltd", "Capital Goods"),
    ("RCF", "Rashtriya Chemicals and Fertilizers Ltd", "Chemicals"),
    ("RECLTD", "REC Ltd", "Financial Services"),
    ("REDINGTON", "Redington Ltd", "IT"),
    ("RELAXO", "Relaxo Footwears Ltd", "Consumer Durables"),
    ("RELIANCE", "Reliance Industries Ltd", "Oil Gas & Consumable Fuels"),
    ("RITES", "RITES Ltd", "Services"),
    ("ROUTE", "Route Mobile Ltd", "IT"),
    ("SAFARI", "Safari Industries (India) Ltd", "Consumer Durables"),
    ("SAIL", "Steel Authority of India Ltd", "Metals & Mining"),
    ("SANOFI", "Sanofi India Ltd", "Healthcare"),
    ("SAPPHIRE", "Sapphire Foods India Ltd", "Consumer Services"),
    ("SCHAEFFLER", "Schaeffler India Ltd", "Capital Goods"),
    ("SHREECEM", "Shree Cement Ltd", "Cement & Cement Products"),
    ("SHREEPRD", "Shree Renuka Sugars Ltd", "FMCG"),
    ("SHYAMMETL", "Shyam Metalics and Energy Ltd", "Metals & Mining"),
    ("SIEMENS", "Siemens Ltd", "Capital Goods"),
    ("SJVN", "SJVN Ltd", "Power"),
    ("SKFINDIA", "SKF India Ltd", "Capital Goods"),
    ("SOLARINDS", "Solar Industries India Ltd", "Chemicals"),
    ("SONACOMS", "Sona BLW Precision Forgings Ltd", "Automobile and Auto Components"),
    ("SRF", "SRF Ltd", "Chemicals"),
    ("STAR", "Star Health and Allied Insurance Company Ltd", "Financial Services"),
    ("STLTECH", "Sterlite Technologies Ltd", "Telecom"),
    ("SUDARSCHEM", "Sudarshan Chemical Industries Ltd", "Chemicals"),
    ("SUMICHEM", "Sumitomo Chemical India Ltd", "Chemicals"),
    ("SUNCLAYLTD", "Sun Pharma Advanced Research Company Ltd", "Healthcare"),
    ("SUNDARMFIN", "Sundaram Finance Ltd", "Financial Services"),
    ("SUNPHARMA", "Sun Pharmaceutical Industries Ltd", "Healthcare"),
    ("SUNTV", "Sun TV Network Ltd", "Media Publishing & Research"),
    ("SUPREMEIND", "Supreme Industries Ltd", "Capital Goods"),
    ("SUZLON", "Suzlon Energy Ltd", "Power"),
    ("SWANENERGY", "Swan Energy Ltd", "Oil Gas & Consumable Fuels"),
    ("SYMPHONY", "Symphony Ltd", "Consumer Durables"),
    ("TANLA", "Tanla Platforms Ltd", "IT"),
    ("TATACHEM", "Tata Chemicals Ltd", "Chemicals"),
    ("TATACOMM", "Tata Communications Ltd", "Telecom"),
    ("TATACONSUM", "Tata Consumer Products Ltd", "FMCG"),
    ("TATAELXSI", "Tata Elxsi Ltd", "IT"),
    ("TATAMOTORS", "Tata Motors Ltd", "Automobile and Auto Components"),
    ("TATAPOWER", "Tata Power Company Ltd", "Power"),
    ("TATASTEEL", "Tata Steel Ltd", "Metals & Mining"),
    ("TCS", "Tata Consultancy Services Ltd", "IT"),
    ("TECHM", "Tech Mahindra Ltd", "IT"),
    ("THERMAX", "Thermax Ltd", "Capital Goods"),
    ("TIMKEN", "Timken India Ltd", "Capital Goods"),
    ("TITAN", "Titan Company Ltd", "Consumer Durables"),
    ("TORNTPHARM", "Torrent Pharmaceuticals Ltd", "Healthcare"),
    ("TORNTPOWER", "Torrent Power Ltd", "Power"),
    ("TRENT", "Trent Ltd", "Consumer Services"),
    ("TRIDENT", "Trident Ltd", "Textile"),
    ("TRITURBINE", "Triveni Turbine Ltd", "Capital Goods"),
    ("TVSHLTD", "TVS Holdings Ltd", "Financial Services"),
    ("TVSMOTOR", "TVS Motor Company Ltd", "Automobile and Auto Components"),
    ("UBL", "United Breweries Ltd", "FMCG"),
    ("ULTRACEMCO", "UltraTech Cement Ltd", "Cement & Cement Products"),
    ("UNIONBANK", "Union Bank of India", "Financial Services"),
    ("UNOMINDA", "Uno Minda Ltd", "Automobile and Auto Components"),
    ("UPL", "UPL Ltd", "Chemicals"),
    ("UTIAMC", "UTI Asset Management Company Ltd", "Financial Services"),
    ("VAIBHAVGBL", "Vaibhav Global Ltd", "Consumer Durables"),
    ("VBL", "Varun Beverages Ltd", "FMCG"),
    ("VEDL", "Vedanta Ltd", "Metals & Mining"),
    ("VIJAYA", "Vijaya Diagnostic Centre Ltd", "Healthcare"),
    ("VOLTAS", "Voltas Ltd", "Consumer Durables"),
    ("VSTIND", "VST Industries Ltd", "FMCG"),
    ("WABAG", "VA Tech Wabag Ltd", "Capital Goods"),
    ("WELCORP", "Welspun Corp Ltd", "Metals & Mining"),
    ("WELENT", "Welspun Enterprises Ltd", "Construction"),
    ("WIPRO", "Wipro Ltd", "IT"),
    ("WOCKPHARMA", "Wockhardt Ltd", "Healthcare"),
    ("XENOTECH", "Xpro India Ltd", "Chemicals"),
    ("YESBANK", "Yes Bank Ltd", "Financial Services"),
    ("ZEEL", "Zee Entertainment Enterprises Ltd", "Media Publishing & Research"),
    ("ZENSARTECH", "Zensar Technologies Ltd", "IT"),
    ("ZOMATO", "Zomato Ltd", "Consumer Services"),
    ("ZYDUSLIFE", "Zydus Lifesciences Ltd", "Healthcare"),
    ("ZYDUSWELL", "Zydus Wellness Ltd", "FMCG"),
]

# Derived ticker list (appends .NS suffix for yfinance)
NIFTY500_TICKERS: list[str] = [f"{sym}.NS" for sym, _, _ in NIFTY500_STATIC]
